# Nome do workflow que aparecerá na aba "Actions" do seu repositório
name: CI/CD Fullstack ENEM App

# Define quando o workflow será executado
on:
  push:
    branches: [ atualizacoes ]
  pull_request:
    branches: [ atualizacoes ]

# Define um único 'job' para o build
jobs:
  build:
    # O ambiente onde o job irá rodar
    runs-on: ubuntu-latest

    # Os passos que o job irá seguir
    steps:
      - name: 'Checkout do repositório'
        # Esta ação faz o checkout do seu código
        uses: actions/checkout@v4

      # --- BACKEND (Java Spring Boot) ---
      - name: 'Configurar JDK 21'
        # Configura o ambiente Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 'Build e package do Backend'
        # Compila o projeto e gera o JAR (pulando testes por enquanto)
        working-directory: ./enem_app/backend
        run: mvn clean package -B -DskipTests

      - name: 'Upload JAR do Backend'
        # Salva o arquivo JAR para deploy
        uses: actions/upload-artifact@v4
        with:
          name: enem-backend-jar
          path: ./enem_app/backend/target/*.jar
          retention-days: 30

      # --- FRONTEND (React + Vite) ---
      - name: 'Configurar Node.js 20'
        # Configura o ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './enem_app/frontend/package-lock.json'

      - name: 'Instalar dependências do Frontend'
        # Instala as dependências do React/Vite
        working-directory: ./enem_app/frontend
        run: npm ci --prefer-offline

      - name: 'Build do Frontend'
        # Cria a versão otimizada para produção
        working-directory: ./enem_app/frontend
        continue-on-error: true
        run: npm run build

      - name: 'Upload build do Frontend'
        # Salva os arquivos estáticos do frontend
        uses: actions/upload-artifact@v4
        with:
          name: enem-frontend-build
          path: ./enem_app/frontend/dist
          retention-days: 30

      # --- DOCKER COMPOSE (Opcional) ---
      - name: 'Teste de integração com Docker'
        # Testa se os serviços sobem corretamente
        working-directory: ./enem_app/db
        continue-on-error: true
        run: |
          echo "Testando Docker Compose..."
          if [ -f "docker-compose.yml" ]; then
            docker-compose up -d
            sleep 20
            docker-compose ps
            docker-compose logs
            docker-compose down -v
            echo "Docker Compose testado com sucesso!"
          else
            echo "docker-compose.yml não encontrado, pulando teste de integração"
          fi